### ISSUE TITLE
No signatures found matching the expected signature for payload

### ISSUE THREAD

**Issue by mulaiko** [integrallis/stripe_event#128]
Hi there,

Just installed your gem, subscribed to a 'checkout.session.completed' event. I'm receiving the following error "No signatures found matching the expected signature for payload" when the event is fired. 

Any pointers on resolving this?

**Comment by mulaiko** [comment]
Found the issue:

I used the signing secret from the Stripe CLI which was different from the one issue in the dashboard. The dashboard signing secret was the correct one to use.

Cheers!

**Comment by vakrolme** [comment]
I ran into this exception in dev environment, and the cause turned out to be that with **stripe-cli** you gotta relogin every 90 days [as mentioned here](https://stripe.com/docs/stripe-cli#login-account). When you do that, a new `whsec_` key is generated, which you gotta extract (it prints to stdout when you run `stripe listen`) and update your .env (or wherever you get `StripeEvent.signing_secrets` from).
