### ISSUE TITLE
Suppressing error in webhooks controller makes testing more difficult

### ISSUE THREAD

**Issue by skalb** [integrallis/stripe_event#56]
In my case, I couldn't figure out why the spec was failing (I hadn't stubbed auth correctly) and had to manually call StripeEvent.instrument in my test.

I'm not super familiar with Engines--is there way to propagate the error and let the client decide how to handle it? And/or add a logging statement?

Thanks for the great work!

Edit: referring to https://github.com/integrallis/stripe_event/blob/master/app/controllers/stripe_event/webhook_controller.rb#L14

**Comment by jasonkarns** [comment]
Agree. This is a problem we're facing as well as we'd like to report stripe_event exceptions to our error monitoring tool.

**Comment by rmm5t** [comment]
@jasonkarns It was closed because the specific feature that was requested was added in 35325f2.

What you're asking for is slightly different. It sounds like you'd like a way to hook into the exception handling and drive it to your monitoring and error-reporting toolchain.

Would you mind opening a new Issue while also elaborating on your specific use-case?

**Comment by jasonkarns** [comment]
roger, thanks!

https://github.com/integrallis/stripe_event/issues/110
