### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by mhenrixon** [integrallis/stripe_event#76]
How about concurrency? Your readme suggest something like

```ruby
StripeEvent.configure do |events|
  events.subscribe 'customer.created', CustomerCreated.new
end
```

How will that work under high load? Is it guaranteed to be thread safe? If not I suggest you update the readme with this information. If that is supposed to be thread safe then lets talk.

**Comment by rmm5t** [comment]
Webhooks by there very nature (because of the potential for retries and queueing delays) do not give any guarantees about the order that they will arrive in. 

Regarding thread safety, is your concern that someone's implementation of `CustomerCreated#call` might rely on instance variables in the instance of `CustomerCreated`?   If so, yeah, using instance variables in the `call` method would be a bad idea. You have two options. 

1. Don't use instance variables when quacking like `Proc#call`.
2. Only use the block syntax for `events.subscribe`:
    ```ruby
        StripeEvent.configure do |events|
          events.subscribe 'customer.created' do |event|
            # do something
          end
        end    
    ```

If you'd like to submit a PR for a README update to help clarify any of this, that would likely be very much appreciated.

**Comment by mhenrixon** [comment]
Thanks @rmm5t, I'll create a PR with some more details around this.

**Comment by invisiblefunnel** [comment]
> Regarding thread safety, is your concern that someone's implementation of CustomerCreated#call might rely on instance variables in the instance of CustomerCreated? If so, yeah, using instance variables in the call method would be a bad idea.

I don't think that is a problem because the listener instance isn't shared across threads. (Someone please correct me if I'm wrong). If your listeners rely on class-level variables, that would not be thread-safe, which is generally true in Ruby.

Also, StripeEvent uses ActiveSupport::Notifications for event dispatch, which is [thread-safe](https://github.com/rails/rails/blob/v5.0.1/activesupport/lib/active_support/notifications/fanout.rb#L9).

**Comment by invisiblefunnel** [comment]
I'm closing this issue. Feel free to reopen if you think it needs more discussion.

**Comment by mhenrixon** [comment]
Forgot about it :) I'll get a PR done soon :)
